import { CATEGORY_LABELS, PILLAR_DESCRIPTIONS } from "./checks";
import type { AuditCheck, CheckStatus, SiteAuditReport } from "./types";

const STATUS_ICON: Record<CheckStatus, string> = {
  pass: "✅",
  warn: "⚠️",
  fail: "❌",
  info: "ℹ️",
};

const SEVERITY_LABEL = { critical: "CRITICAL", warning: "WARNING", notice: "NOTICE" };

function scoreBar(score: number): string {
  const filled = Math.round(score / 10);
  return "█".repeat(filled) + "░".repeat(10 - filled);
}

function grade(score: number): string {
  if (score >= 90) return "A";
  if (score >= 80) return "B";
  if (score >= 70) return "C";
  if (score >= 60) return "D";
  return "F";
}

export function formatReportMarkdown(report: SiteAuditReport): string {
  const lines: string[] = [
    `# SEO & GEO Audit Report`,
    ``,
    `> **${report.domain}** — Comprehensive search & AI visibility analysis`,
    ``,
    `| | |`,
    `|---|---|`,
    `| **Target URL** | ${report.targetUrl} |`,
    `| **Generated** | ${new Date(report.generatedAt).toLocaleString()} |`,
    `| **Scan time** | ${(report.metrics.scanDurationMs / 1000).toFixed(1)}s |`,
    `| **Pages scanned** | ${report.metrics.pagesScanned} |`,
    `| **Total checks** | ${report.metrics.totalChecks} |`,
    `| **Words analyzed** | ${report.metrics.wordsAnalyzed.toLocaleString()} |`,
    ``,
    `## Executive Summary`,
    ``,
    `| Score | Value | Grade |`,
    `|-------|-------|-------|`,
    `| **Overall Health** | ${report.overallScore}/100 | ${grade(report.overallScore)} |`,
    `| **SEO Score** | ${report.seoScore}/100 | ${grade(report.seoScore)} |`,
    `| **GEO Score** | ${report.geoScore}/100 | ${grade(report.geoScore)} |`,
    ``,
    `| Status | Count |`,
    `|--------|-------|`,
    `| ✅ Passed | ${report.summary.pass} |`,
    `| ⚠️ Warnings | ${report.summary.warn} |`,
    `| ❌ Critical | ${report.summary.fail} |`,
    `| ℹ️ Notices | ${report.summary.info} |`,
    ``,
    `## AI Platform Readiness`,
    ``,
    `| Platform | Score | Assessment |`,
    `|----------|-------|------------|`,
    ...report.platformScores.map((p) => `| ${p.label} | ${p.score}/100 ${scoreBar(p.score)} | ${p.summary} |`),
    ``,
    `## Pillar Breakdown`,
    ``,
  ];

  for (const [cat, score] of Object.entries(report.categoryScores)) {
    const label = CATEGORY_LABELS[cat as keyof typeof CATEGORY_LABELS];
    const desc = PILLAR_DESCRIPTIONS[cat as keyof typeof PILLAR_DESCRIPTIONS];
    lines.push(`### ${label} — ${score}/100 ${scoreBar(score)}`, ``, desc, ``);
  }

  lines.push(`## Prioritized Action Plan`, ``);
  if (report.actionPlan.length === 0) lines.push(`*No critical issues — site is in strong shape.*`, ``);
  else {
    for (const item of report.actionPlan) {
      lines.push(`### ${item.priority}. [${SEVERITY_LABEL[item.severity]}] ${item.title}`, ``);
      lines.push(`**Impact:** ${item.impact} · **Category:** ${CATEGORY_LABELS[item.category]}${item.pagePath ? ` · **Page:** \`${item.pagePath}\`` : ""}`, ``);
      lines.push(item.recommendation, ``);
      if (item.fixSnippet) lines.push("```html", item.fixSnippet, "```", ``);
    }
  }

  lines.push(`## Site-Wide Findings`, ``);
  for (const c of report.siteChecks) lines.push(formatCheckLine(c));

  for (const page of report.pages) {
    lines.push(
      ``,
      `## Page Analysis: \`${page.snapshot.path}\``,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| Score | ${page.score}/100 |`,
      `| Title | ${page.snapshot.title} |`,
      `| Words | ${page.snapshot.wordCount} |`,
      `| H1 | ${page.snapshot.h1Texts[0] ?? "—"} |`,
      `| Schema types | ${page.snapshot.schemaTypes.join(", ") || "—"} |`,
      ``,
    );
    for (const c of page.checks) lines.push(formatCheckLine(c));
  }

  lines.push(``, `---`, `*Report generated by Adrevnview SEO & GEO Report Generator · ${report.metrics.totalChecks} checks*`);
  return lines.join("\n");
}

function formatCheckLine(c: AuditCheck): string {
  const icon = STATUS_ICON[c.status];
  let line = `${icon} **${c.title}** — ${c.detail}`;
  if (c.recommendation) line += `\n   → *${c.recommendation}*`;
  return line;
}

export function formatReportJson(report: SiteAuditReport): string {
  return JSON.stringify(report, null, 2);
}

export function downloadText(filename: string, content: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function formatReportHtml(report: SiteAuditReport): string {
  const md = formatReportMarkdown(report);
  const escaped = md
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\n\n/g, "</p><p>")
    .replace(/\n/g, "<br>");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>SEO/GEO Report — ${report.domain}</title>
<style>body{font-family:system-ui;max-width:900px;margin:40px auto;padding:0 24px;line-height:1.6;color:#111}h1{color:#4f46e5}h2{border-bottom:1px solid #e5e7eb;padding-bottom:8px}table{border-collapse:collapse;width:100%;margin:16px 0}td,th{border:1px solid #e5e7eb;padding:8px 12px;text-align:left}th{background:#f9fafb}</style></head>
<body><p>${escaped}</p></body></html>`;
}
